from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RetailSource:
    key: str
    name: str
    source_type: str
    priority: int
    categories: tuple[str, ...]
    notes: str


SOURCE_API = "api"
SOURCE_FEED = "feed"
SOURCE_MONITOR = "monitor"
SOURCE_PARTNER = "partner_access"


RETAIL_SOURCES: tuple[RetailSource, ...] = (
    RetailSource(
        key="amazon",
        name="Amazon",
        source_type=SOURCE_API,
        priority=100,
        categories=("electronics", "computer_parts", "business", "household", "automotive", "warehouse_deals"),
        notes="Use official/product-data providers for ASIN, price, offers, and primary images where available.",
    ),
    RetailSource(
        key="best_buy",
        name="Best Buy",
        source_type=SOURCE_API,
        priority=95,
        categories=("electronics", "computer_parts", "gaming", "appliances"),
        notes="Strong source for GPUs, CPUs, monitors, appliances, open-box and product-catalog anomalies.",
    ),
    RetailSource(
        key="walmart",
        name="Walmart",
        source_type=SOURCE_PARTNER,
        priority=94,
        categories=("electronics", "household", "automotive", "grocery", "clearance", "apparel", "sneakers"),
        notes="Watch online pricing, marketplace seller changes, rollback/clearance mismatches, and store-specific later.",
    ),
    RetailSource(
        key="target",
        name="Target",
        source_type=SOURCE_MONITOR,
        priority=88,
        categories=("electronics", "home", "toys", "household", "clearance", "apparel"),
        notes="Monitor hot categories and clearance-like online price drops where allowed.",
    ),
    RetailSource(
        key="costco",
        name="Costco",
        source_type=SOURCE_MONITOR,
        priority=92,
        categories=("warehouse", "electronics", "appliances", "jewelry", "bulk", "automotive", "apparel"),
        notes="Warehouse-club pricing, member-only offers, gold/jewelry, appliances, and bulk misprices.",
    ),
    RetailSource(
        key="sams_club",
        name="Sam's Club",
        source_type=SOURCE_MONITOR,
        priority=91,
        categories=("warehouse", "electronics", "bulk", "household", "automotive", "apparel"),
        notes="Member pricing, instant savings, bulk packs, and checkout-only pricing anomalies.",
    ),
    RetailSource(
        key="bjs",
        name="BJ's Wholesale Club",
        source_type=SOURCE_MONITOR,
        priority=86,
        categories=("warehouse", "bulk", "household", "appliances", "automotive"),
        notes="Warehouse-club and coupon-stack anomalies.",
    ),
    RetailSource(
        key="woot",
        name="Woot",
        source_type=SOURCE_MONITOR,
        priority=89,
        categories=("electronics", "home", "tools", "clearance", "apparel"),
        notes="Fast-moving online deals, Amazon-owned closeouts, and limited-quantity anomalies.",
    ),
    RetailSource(
        key="newegg",
        name="Newegg",
        source_type=SOURCE_MONITOR,
        priority=94,
        categories=("computer_parts", "electronics", "gaming"),
        notes="GPUs, CPUs, RAM, SSDs, bundles, combo errors, and marketplace seller changes.",
    ),
    RetailSource(
        key="micro_center",
        name="Micro Center",
        source_type=SOURCE_MONITOR,
        priority=90,
        categories=("computer_parts", "electronics", "gaming"),
        notes="CPU/GPU/RAM/SSD deals, bundles, local inventory, and store-specific pricing later.",
    ),
    RetailSource(
        key="bh_photo",
        name="B&H Photo",
        source_type=SOURCE_MONITOR,
        priority=84,
        categories=("electronics", "cameras", "computer_parts", "pro_audio"),
        notes="Pro electronics, cameras, storage, and checkout-price anomalies.",
    ),
    RetailSource(
        key="adorama",
        name="Adorama",
        source_type=SOURCE_MONITOR,
        priority=82,
        categories=("electronics", "cameras", "computer_parts", "pro_audio"),
        notes="Camera/computer bundles, coupon mistakes, and pro-equipment price drops.",
    ),
    RetailSource(
        key="apple_store",
        name="Apple Store",
        source_type=SOURCE_MONITOR,
        priority=90,
        categories=("electronics", "apple", "phones", "computers", "tablets", "wearables"),
        notes="Apple direct refurbished, education/business pricing, checkout issues, and accessory misprices.",
    ),
    RetailSource(
        key="samsung",
        name="Samsung",
        source_type=SOURCE_MONITOR,
        priority=93,
        categories=("electronics", "phones", "tablets", "tvs", "appliances", "wearables", "monitors"),
        notes="Brand-direct phones, tablets, TVs, appliances, monitors, trade-in/coupon stack anomalies.",
    ),
    RetailSource(
        key="lg",
        name="LG",
        source_type=SOURCE_MONITOR,
        priority=88,
        categories=("electronics", "tvs", "appliances", "monitors", "home"),
        notes="Brand-direct TVs, OLEDs, appliances, monitors, coupon stacks, and checkout price mismatches.",
    ),
    RetailSource(
        key="sony",
        name="Sony",
        source_type=SOURCE_MONITOR,
        priority=86,
        categories=("electronics", "gaming", "cameras", "audio", "tvs"),
        notes="PlayStation, cameras, headphones, TVs, bundles, and official-store price anomalies.",
    ),
    RetailSource(
        key="microsoft_store",
        name="Microsoft Store",
        source_type=SOURCE_MONITOR,
        priority=86,
        categories=("electronics", "gaming", "computers", "software", "business"),
        notes="Xbox, Surface, software, business pricing, and bundle/coupon anomalies.",
    ),
    RetailSource(
        key="google_store",
        name="Google Store",
        source_type=SOURCE_MONITOR,
        priority=80,
        categories=("electronics", "phones", "smart_home", "wearables"),
        notes="Pixel, Nest, Fitbit, trade-in and coupon-stack anomalies.",
    ),
    RetailSource(
        key="msi_store",
        name="MSI Store",
        source_type=SOURCE_MONITOR,
        priority=93,
        categories=("computer_parts", "gaming", "laptops"),
        notes="Official manufacturer store for GPU/laptop/accessory price errors.",
    ),
    RetailSource(
        key="asus_store",
        name="ASUS Store",
        source_type=SOURCE_MONITOR,
        priority=86,
        categories=("computer_parts", "gaming", "laptops", "monitors"),
        notes="ROG laptops, GPUs, monitors, motherboards, bundles, and official-store price errors.",
    ),
    RetailSource(
        key="razer",
        name="Razer",
        source_type=SOURCE_MONITOR,
        priority=80,
        categories=("gaming", "laptops", "peripherals", "electronics"),
        notes="Gaming laptops, keyboards, mice, headsets, coupon-stack and checkout anomalies.",
    ),
    RetailSource(
        key="dell",
        name="Dell",
        source_type=SOURCE_MONITOR,
        priority=85,
        categories=("computers", "monitors", "business", "electronics"),
        notes="Stacking coupons, business pricing, monitor/laptop misprices.",
    ),
    RetailSource(
        key="lenovo",
        name="Lenovo",
        source_type=SOURCE_MONITOR,
        priority=82,
        categories=("computers", "business", "electronics"),
        notes="Business-account pricing, laptops, monitors, coupons, and cart price mismatches.",
    ),
    RetailSource(
        key="hp",
        name="HP",
        source_type=SOURCE_MONITOR,
        priority=80,
        categories=("computers", "printers", "business", "electronics"),
        notes="Laptops, printers, monitors, business pricing, coupon stacks, and bundle errors.",
    ),
    RetailSource(
        key="nike",
        name="Nike",
        source_type=SOURCE_MONITOR,
        priority=90,
        categories=("sneakers", "apparel", "sportswear", "streetwear"),
        notes="Sneaker drops, clearance, member pricing, coupon stacks, and pricing glitches on high-demand shoes/apparel.",
    ),
    RetailSource(
        key="adidas",
        name="Adidas",
        source_type=SOURCE_MONITOR,
        priority=88,
        categories=("sneakers", "apparel", "sportswear", "streetwear"),
        notes="Sneakers, Yeezy-style demand lanes where applicable, outlet pricing, coupon stacks, and member-price errors.",
    ),
    RetailSource(
        key="puma",
        name="Puma",
        source_type=SOURCE_MONITOR,
        priority=78,
        categories=("sneakers", "apparel", "sportswear"),
        notes="Sneakers, apparel, outlet pricing, coupon stacking, and clearance anomalies.",
    ),
    RetailSource(
        key="new_balance",
        name="New Balance",
        source_type=SOURCE_MONITOR,
        priority=84,
        categories=("sneakers", "apparel", "sportswear", "streetwear"),
        notes="High-demand sneaker models, collabs, outlet pricing, and checkout anomalies.",
    ),
    RetailSource(
        key="under_armour",
        name="Under Armour",
        source_type=SOURCE_MONITOR,
        priority=76,
        categories=("apparel", "sportswear", "sneakers"),
        notes="Athletic apparel, shoes, outlet pricing, and coupon-stack mistakes.",
    ),
    RetailSource(
        key="reebok",
        name="Reebok",
        source_type=SOURCE_MONITOR,
        priority=72,
        categories=("sneakers", "apparel", "sportswear"),
        notes="Sneakers, apparel, outlet pricing, and clearance/coupon anomalies.",
    ),
    RetailSource(
        key="foot_locker",
        name="Foot Locker",
        source_type=SOURCE_MONITOR,
        priority=87,
        categories=("sneakers", "apparel", "streetwear"),
        notes="Sneaker demand, drops, restocks, markdowns, and cart/checkout anomalies.",
    ),
    RetailSource(
        key="champs",
        name="Champs Sports",
        source_type=SOURCE_MONITOR,
        priority=80,
        categories=("sneakers", "apparel", "streetwear"),
        notes="Sneakers, sportswear, markdowns, and checkout anomalies.",
    ),
    RetailSource(
        key="jd_sports",
        name="JD Sports",
        source_type=SOURCE_MONITOR,
        priority=83,
        categories=("sneakers", "apparel", "streetwear"),
        notes="Sneaker drops, restocks, markdowns, and cart/checkout anomalies.",
    ),
    RetailSource(
        key="finish_line",
        name="Finish Line",
        source_type=SOURCE_MONITOR,
        priority=82,
        categories=("sneakers", "apparel", "streetwear"),
        notes="Sneakers, drops/restocks, clearance, coupons, and checkout issues.",
    ),
    RetailSource(
        key="dicks_sporting_goods",
        name="Dick's Sporting Goods",
        source_type=SOURCE_MONITOR,
        priority=84,
        categories=("sportswear", "sneakers", "outdoor", "fitness", "apparel"),
        notes="Sneakers, sports equipment, outdoor gear, clearance, and coupon-stack anomalies.",
    ),
    RetailSource(
        key="fanatics",
        name="Fanatics",
        source_type=SOURCE_MONITOR,
        priority=76,
        categories=("apparel", "sportswear", "collectibles"),
        notes="Team apparel, jerseys, collectibles, coupon stacks, and pricing errors.",
    ),
    RetailSource(
        key="lululemon",
        name="lululemon",
        source_type=SOURCE_MONITOR,
        priority=78,
        categories=("apparel", "sportswear", "premium_apparel"),
        notes="Premium athletic apparel, markdown drops, and checkout anomalies.",
    ),
    RetailSource(
        key="macys",
        name="Macy's",
        source_type=SOURCE_MONITOR,
        priority=82,
        categories=("apparel", "jewelry", "fragrance", "home", "watches"),
        notes="Jewelry, watches, fragrances, apparel, coupon stacking, and clearance anomalies.",
    ),
    RetailSource(
        key="kohls",
        name="Kohl's",
        source_type=SOURCE_MONITOR,
        priority=80,
        categories=("apparel", "home", "jewelry", "toys", "small_appliances"),
        notes="Coupon stacking, Kohl's Cash interactions, clearance, and small appliance misprices.",
    ),
    RetailSource(
        key="nordstrom_rack",
        name="Nordstrom Rack",
        source_type=SOURCE_MONITOR,
        priority=78,
        categories=("apparel", "sneakers", "designer", "watches", "jewelry"),
        notes="Designer markdowns, sneakers, watches, jewelry, and clearance price errors.",
    ),
    RetailSource(
        key="jcpenney",
        name="JCPenney",
        source_type=SOURCE_MONITOR,
        priority=76,
        categories=("apparel", "jewelry", "home", "watches"),
        notes="Jewelry, home goods, apparel, coupon stacks, and clearance anomalies.",
    ),
    RetailSource(
        key="zales",
        name="Zales",
        source_type=SOURCE_MONITOR,
        priority=78,
        categories=("jewelry", "gold_jewelry", "diamonds", "watches"),
        notes="Gold, diamonds, chains, rings, coupon mistakes, and price/melt-value anomalies.",
    ),
    RetailSource(
        key="kay",
        name="Kay Jewelers",
        source_type=SOURCE_MONITOR,
        priority=78,
        categories=("jewelry", "gold_jewelry", "diamonds", "watches"),
        notes="Gold, diamonds, chains, watches, coupon mistakes, and pricing anomalies.",
    ),
    RetailSource(
        key="jared",
        name="Jared",
        source_type=SOURCE_MONITOR,
        priority=76,
        categories=("jewelry", "gold_jewelry", "diamonds", "watches"),
        notes="Fine jewelry, gold, diamonds, watches, and checkout/coupon mistakes.",
    ),
    RetailSource(
        key="blue_nile",
        name="Blue Nile",
        source_type=SOURCE_MONITOR,
        priority=72,
        categories=("jewelry", "diamonds", "gold_jewelry"),
        notes="Diamonds, gold jewelry, pricing anomalies, and promo mistakes.",
    ),
    RetailSource(
        key="home_depot",
        name="Home Depot",
        source_type=SOURCE_MONITOR,
        priority=90,
        categories=("tools", "home", "appliances", "automotive", "clearance"),
        notes="Tools, appliances, bulk items, online clearance, and later store-specific inventory.",
    ),
    RetailSource(
        key="lowes",
        name="Lowe's",
        source_type=SOURCE_MONITOR,
        priority=89,
        categories=("tools", "home", "appliances", "automotive", "clearance"),
        notes="Tools, appliances, online clearance, coupon stacking, and local inventory later.",
    ),
    RetailSource(
        key="harbor_freight",
        name="Harbor Freight",
        source_type=SOURCE_MONITOR,
        priority=80,
        categories=("tools", "automotive", "garage"),
        notes="Tool pricing, coupons, and clearance anomalies.",
    ),
    RetailSource(
        key="tractor_supply",
        name="Tractor Supply Co.",
        source_type=SOURCE_MONITOR,
        priority=74,
        categories=("tools", "outdoor", "automotive", "farm", "home"),
        notes="Tools, outdoor equipment, farm supplies, generators, and clearance anomalies.",
    ),
    RetailSource(
        key="autozone",
        name="AutoZone",
        source_type=SOURCE_MONITOR,
        priority=83,
        categories=("automotive", "motor_oil", "fluids", "parts"),
        notes="Motor oil, fluids, batteries, parts, multi-buy mistakes, and coupon-stack anomalies.",
    ),
    RetailSource(
        key="advance_auto",
        name="Advance Auto Parts",
        source_type=SOURCE_MONITOR,
        priority=83,
        categories=("automotive", "motor_oil", "fluids", "parts"),
        notes="Motor oil, filters, batteries, fluids, and code/coupon-stack mistakes.",
    ),
    RetailSource(
        key="oreilly",
        name="O'Reilly Auto Parts",
        source_type=SOURCE_MONITOR,
        priority=80,
        categories=("automotive", "motor_oil", "fluids", "parts"),
        notes="Auto fluids, parts, and regional pricing anomalies.",
    ),
    RetailSource(
        key="napa",
        name="NAPA Auto Parts",
        source_type=SOURCE_MONITOR,
        priority=78,
        categories=("automotive", "motor_oil", "fluids", "parts"),
        notes="Auto fluids, parts, shop supplies, and business-account pricing.",
    ),
    RetailSource(
        key="rockauto",
        name="RockAuto",
        source_type=SOURCE_MONITOR,
        priority=74,
        categories=("automotive", "parts"),
        notes="Auto parts pricing, closeouts, and catalog mismatch anomalies.",
    ),
    RetailSource(
        key="staples",
        name="Staples",
        source_type=SOURCE_MONITOR,
        priority=78,
        categories=("business", "office", "electronics", "bulk"),
        notes="Business supplies, bulk packs, toner, chairs, electronics, and coupon mistakes.",
    ),
    RetailSource(
        key="office_depot",
        name="Office Depot / OfficeMax",
        source_type=SOURCE_MONITOR,
        priority=76,
        categories=("business", "office", "electronics", "bulk"),
        notes="Business supplies, bulk pricing, coupons, and office electronics.",
    ),
)


def source_by_key(key: str) -> RetailSource | None:
    normalized = key.strip().lower()
    return next((source for source in RETAIL_SOURCES if source.key == normalized), None)


def sources_for_category(category: str) -> list[RetailSource]:
    normalized = category.strip().lower()
    return [source for source in RETAIL_SOURCES if normalized in source.categories]


def high_priority_sources(limit: int = 10) -> list[RetailSource]:
    return sorted(RETAIL_SOURCES, key=lambda source: source.priority, reverse=True)[:limit]
